---

port_profiles:
  PP-DOT1X:
    mode: "trunk phone"
    spanning_tree_portfast: edge
    spanning_tree_bpduguard: enabled
    dot1x:
      port_control: auto
      reauthentication: true
      pae:
        mode: authenticator
      host_mode:
        mode: multi-host
        multi_host_authenticated: true
      mac_based_authentication:
        enabled: true
      timeout:
        reauth_period: server
        tx_period: 3
      reauthorization_request_limit: 3

network_ports:

# ---------------- leaf1/2 ----------------

  - switches:
      - leaf[12] # regex match leaf1 & leaf2
    switch_ports:
      - Ethernet1-48
    profile: PP-DOT1X
    native_vlan: 10
    structured_config:
      phone:
        trunk: untagged
        vlan: 15
    dot1x:
      authentication_failure:
        action: allow
        allow_vlan: 999

# ---------------- leaf3/4 ----------------

  - switches:
      - leaf[34] # regex match leaf3 & leaf4
    switch_ports:
      - Ethernet1-48
    profile: PP-DOT1X
    native_vlan: 20
    structured_config:
      phone:
        trunk: untagged
        vlan: 25
    dot1x:
      authentication_failure:
        action: allow
        allow_vlan: 999